#! /usr/bin/env python
import sys
import requests

url = sys.argv[1]

payload = { 'key' : 'value', 'first_name' : 'Ari', 'last_name' : 'Polavarapu' }
r = requests.post(url, data=payload)

print r.status_code
print r.text


